version: 0.1

StackName: todo-list-aws
Region: us-east-1
S3Bucket: todo-list-aws

default:
  Stage: staging
  ConfirmChangeset: true
  AllowIAMRoleCreation: true
  SaveConfig: true

capabilities:
  - CAPABILITY_IAM

parameter_overrides:
  Stage: staging
